package com.qfc.rag;
import com.qfc.auth.LoginUser; import com.qfc.common.ApiException; import com.qfc.config.QfcStorageProperties; import com.qfc.file.ProjectFile; import com.qfc.file.ProjectFileMapper; import com.qfc.project.Project; import com.qfc.project.ProjectMapper; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.time.LocalDateTime; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.util.StringUtils;
@Service public class RagService {
 private final ProjectMapper projects; private final ProjectMemberMapper members; private final ProjectFileMapper files; private final KnowledgeFileMapper knowledge; private final KnowledgeChunkMapper chunks; private final QfcStorageProperties storage;
 public RagService(ProjectMapper p,ProjectMemberMapper m,ProjectFileMapper f,KnowledgeFileMapper k,KnowledgeChunkMapper c,QfcStorageProperties s){projects=p;members=m;files=f;knowledge=k;chunks=c;storage=s;}
 public void requireAccess(Long projectId,LoginUser u,boolean edit){Project p=projects.selectById(projectId); if(p==null||p.isDeleted()) throw new ApiException("PROJECT_NOT_FOUND","项目不存在",404); if(p.getOwnerUserId()!=null&&p.getOwnerUserId().equals(u.getId()))return; ProjectMember m=members.find(projectId,u.getId()); if(m==null|| (edit&&!"EDITOR".equals(m.getRole()))) throw new ApiException("FORBIDDEN","无项目权限",403);}
 public void include(Long projectId,Long fileId,LoginUser u){requireAccess(projectId,u,true); ProjectFile f=files.selectById(fileId); if(f==null||!projectId.equals(f.getProjectId())) throw new ApiException("FILE_NOT_FOUND","文件不存在",404); if(isSensitive(f)) throw new ApiException("SENSITIVE_FILE","敏感文件不可纳入问答",400); KnowledgeFile k=knowledge.find(projectId,fileId); if(k==null){k=new KnowledgeFile();k.setProjectId(projectId);k.setFileId(fileId);k.setCreatedAt(LocalDateTime.now());} k.setIncluded(true);k.setSensitive(false);k.setStatus("PENDING");k.setUpdatedAt(LocalDateTime.now());k.setErrorMessage(""); if(k.getId()==null)knowledge.insert(k);else knowledge.updateById(k); index(k,f);}
 public Map<String,Object> chat(Long projectId,String q,LoginUser u){requireAccess(projectId,u,false); if(!StringUtils.hasText(q))throw new ApiException("INVALID_QUERY","问题不能为空",400); List<Map<String,Object>> refs=new ArrayList<>(); for(KnowledgeFile k:knowledge.available(projectId)){for(KnowledgeChunk c:chunks.search(k.getId(),q.trim())){ProjectFile f=files.selectById(k.getFileId()); if(f!=null&&projectId.equals(f.getProjectId())){Map<String,Object> r=new LinkedHashMap<>();r.put("fileId",f.getId());r.put("relativePath",f.getRelativePath());r.put("quote",c.getContent());r.put("locator",c.getLocator());refs.add(r);}}} Map<String,Object> out=new LinkedHashMap<>();out.put("answerId",UUID.randomUUID().toString());out.put("answer",refs.isEmpty()?"资料中没有找到":"根据已纳入资料找到相关内容");out.put("references",refs);return out;}
 private void index(KnowledgeFile k,ProjectFile f){k.setStatus("INDEXING");knowledge.updateById(k);try{String ext=f.getFileExt()==null?"":f.getFileExt().toLowerCase(Locale.ROOT); if(!(ext.equals("md")||ext.equals("markdown")||ext.equals("txt")))throw new IllegalArgumentException("仅支持 Markdown/TXT；Word 抽取将在下一小步接入"); Path p=Paths.get(storage.getRoot()).resolve(f.getStoragePath()).normalize(); if(!Files.exists(p))throw new IllegalArgumentException("文件不存在"); String s=new String(Files.readAllBytes(p),StandardCharsets.UTF_8); chunks.deleteByKnowledgeFileId(k.getId()); int n=0; for(int i=0;i<s.length();i+=1000){KnowledgeChunk c=new KnowledgeChunk();c.setKnowledgeFileId(k.getId());c.setChunkNo(n++);c.setContent(s.substring(i,Math.min(s.length(),i+1000)));c.setLocator("chunk:"+n);c.setCreatedAt(LocalDateTime.now());chunks.insert(c);}k.setStatus("AVAILABLE");k.setIndexedAt(LocalDateTime.now());k.setUpdatedAt(LocalDateTime.now());knowledge.updateById(k);}catch(Exception e){k.setStatus("FAILED");k.setErrorMessage(e.getMessage()==null?"索引失败":e.getMessage());k.setUpdatedAt(LocalDateTime.now());knowledge.updateById(k);}}
 private boolean isSensitive(ProjectFile f){String n=(f.getRelativePath()+"/"+f.getOriginalName()).toLowerCase(Locale.ROOT);return n.matches(".*(^|[/\\\\])(id_rsa|.*\\.(pem|key|p12|jks|env|sql|zip|7z|rar))$");}
}
