import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const spaceViewSource = readFileSync(resolve('src/views/SpaceView.vue'), 'utf8')
const fileTreeSource = readFileSync(resolve('src/components/FileTreeList.vue'), 'utf8')

assert.match(spaceViewSource, /type ProjectPanel = 'list' \| 'edit' \| 'files'/)
assert.match(spaceViewSource, /const activeProjectPanel = ref<ProjectPanel>\('list'\)/)
assert.match(spaceViewSource, /const issueError = ref\(''\)/)
assert.match(spaceViewSource, /function returnToProjectList\(\)/)
assert.match(spaceViewSource, /async function openProjectFiles\(project: ProjectView\)/)
assert.match(spaceViewSource, /function openProjectEditor\(project: ProjectView\)/)
assert.match(spaceViewSource, /async function handleDeleteProject\(project: ProjectView\)/)
assert.match(spaceViewSource, /const selectedFileIds = ref<number\[\]>\(\[\]\)/)
assert.match(spaceViewSource, /const selectedFiles = computed/)
assert.match(spaceViewSource, /const bulkDeletingFiles = ref\(false\)/)
assert.match(spaceViewSource, /async function handleDeleteSelectedFiles\(\)/)
assert.match(spaceViewSource, /async function handleDownloadSelectedFiles\(\)/)
assert.match(spaceViewSource, /downloadSpaceProjectFilesArchive/)
assert.match(spaceViewSource, /const requestedFileIds = \[\.\.\.selectedFileIds\.value\]/)
assert.match(spaceViewSource, /const requestedCount = requestedFileIds\.length/)
assert.match(spaceViewSource, /prepareSpaceProjectUploadFiles/)
assert.match(spaceViewSource, /getSpaceUploadLimits/)
assert.match(spaceViewSource, /uploadFailures/)
assert.match(spaceViewSource, /上传失败清单/)
assert.match(spaceViewSource, /continue/)
assert.match(spaceViewSource, /preparedUpload\.ignoredCount/)
assert.match(spaceViewSource, /已忽略 \$\{preparedUpload\.ignoredCount\} 个/)
assert.match(spaceViewSource, /v-model:selected-file-ids="selectedFileIds"/)
assert.match(spaceViewSource, /:selection-disabled="bulkDeletingFiles \|\| downloadingSelectedFiles"/)
assert.match(spaceViewSource, /批量删除/)
assert.match(spaceViewSource, /批量下载/)
assert.match(spaceViewSource, /下载整个项目/)
assert.match(spaceViewSource, /deleteSpaceProject/)
assert.match(spaceViewSource, />编辑</)
assert.match(spaceViewSource, /'删除'/)
assert.match(spaceViewSource, />返回项目列表</)
assert.match(spaceViewSource, /activeProjectPanel === 'list'/)
assert.match(spaceViewSource, /activeProjectPanel === 'edit'/)
assert.match(spaceViewSource, /activeProjectPanel === 'files'/)
assert.match(spaceViewSource, /@click\.stop="openProjectEditor\(project\)"/)
assert.match(spaceViewSource, /@click\.stop="handleDeleteProject\(project\)"/)
assert.doesNotMatch(spaceViewSource, /error\.value = caught instanceof Error \? caught\.message : '提问记录加载失败'/)
assert.match(spaceViewSource, /issueError\.value = '提问记录暂不可用'/)
assert.match(fileTreeSource, /selectable\?: boolean/)
assert.match(fileTreeSource, /selectedFileIds\?: number\[\]/)
assert.match(fileTreeSource, /'update:selectedFileIds': \[fileIds: number\[\]\]/)
assert.match(fileTreeSource, /function selectAllFiles\(\)/)
assert.match(fileTreeSource, /function clearFileSelection\(\)/)
assert.match(fileTreeSource, /type="checkbox"/)

console.log('Space project management checks passed.')
